# Generated by Django 5.1.2 on 2025-03-24 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_schedule_timeslot_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.DateTimeField(),
        ),
    ]
