# Generated by Django 5.1.2 on 2025-03-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_alter_timeslot_end_time_alter_timeslot_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.CharField(
                choices=[
                    ("09:00:00", "9:00 AM"),
                    ("12:00:00", "12:00 PM"),
                    ("15:00:00", "3:00 PM"),
                    ("18:00:00", "6:00 PM"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.CharField(
                choices=[
                    ("09:00:00", "9:00 AM"),
                    ("12:00:00", "12:00 PM"),
                    ("15:00:00", "3:00 PM"),
                    ("18:00:00", "6:00 PM"),
                ],
                max_length=8,
            ),
        ),
    ]
