# Generated by Django 5.1.2 on 2025-03-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_timeslot_end_time_alter_timeslot_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.CharField(max_length=8),
        ),
    ]
