# Generated by Django 5.1.2 on 2025-03-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_alter_timeslot_end_time_alter_timeslot_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.CharField(
                choices=[
                    ("06:00 AM", "06:00 AM"),
                    ("06:30 AM", "06:30 AM"),
                    ("07:00 AM", "07:00 AM"),
                    ("07:30 AM", "07:30 AM"),
                    ("08:00 AM", "08:00 AM"),
                    ("08:30 AM", "08:30 AM"),
                    ("09:00 AM", "09:00 AM"),
                    ("09:30 AM", "09:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("01:00 PM", "01:00 PM"),
                    ("01:30 PM", "01:30 PM"),
                    ("02:00 PM", "02:00 PM"),
                    ("02:30 PM", "02:30 PM"),
                    ("03:00 PM", "03:00 PM"),
                    ("03:30 PM", "03:30 PM"),
                    ("04:00 PM", "04:00 PM"),
                    ("04:30 PM", "04:30 PM"),
                    ("05:00 PM", "05:00 PM"),
                    ("05:30 PM", "05:30 PM"),
                    ("06:00 PM", "06:00 PM"),
                    ("06:30 PM", "06:30 PM"),
                    ("07:00 PM", "07:00 PM"),
                    ("07:30 PM", "07:30 PM"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="start_time",
            field=models.CharField(
                choices=[
                    ("06:00 AM", "06:00 AM"),
                    ("06:30 AM", "06:30 AM"),
                    ("07:00 AM", "07:00 AM"),
                    ("07:30 AM", "07:30 AM"),
                    ("08:00 AM", "08:00 AM"),
                    ("08:30 AM", "08:30 AM"),
                    ("09:00 AM", "09:00 AM"),
                    ("09:30 AM", "09:30 AM"),
                    ("10:00 AM", "10:00 AM"),
                    ("10:30 AM", "10:30 AM"),
                    ("11:00 AM", "11:00 AM"),
                    ("11:30 AM", "11:30 AM"),
                    ("12:00 PM", "12:00 PM"),
                    ("12:30 PM", "12:30 PM"),
                    ("01:00 PM", "01:00 PM"),
                    ("01:30 PM", "01:30 PM"),
                    ("02:00 PM", "02:00 PM"),
                    ("02:30 PM", "02:30 PM"),
                    ("03:00 PM", "03:00 PM"),
                    ("03:30 PM", "03:30 PM"),
                    ("04:00 PM", "04:00 PM"),
                    ("04:30 PM", "04:30 PM"),
                    ("05:00 PM", "05:00 PM"),
                    ("05:30 PM", "05:30 PM"),
                    ("06:00 PM", "06:00 PM"),
                    ("06:30 PM", "06:30 PM"),
                    ("07:00 PM", "07:00 PM"),
                    ("07:30 PM", "07:30 PM"),
                ],
                max_length=8,
            ),
        ),
    ]
