# Generated by Django 5.1.2 on 2025-03-27 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_classes_coach_review'),
        ('app', '0007_products'),
    ]

    operations = [
    ]
