<<<<<<< HEAD
# Generated by Django 5.1.2 on 2025-03-27 19:10
=======
# Generated by Django 5.1.2 on 2025-03-27 15:51
>>>>>>> 855b08a6bd1e23d0400e10cde9273870f5f569ec

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('app', '0007_classes_coach_review'),
        ('app', '0007_products'),
    ]

    operations = [
    ]
=======
        ("app", "0007_classes_coach_review"),
        ("app", "0007_products"),
    ]

    operations = []
>>>>>>> 855b08a6bd1e23d0400e10cde9273870f5f569ec
