# Generated by Django 5.1.2 on 2025-03-28 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_merge_0007_classes_coach_review_0007_products"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.coach",
            ),
        ),
        migrations.AlterField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="classes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
