# Generated by Django 5.1.2 on 2025-03-28 14:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_classes_coach_alter_classes_students"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="students",
            field=models.ManyToManyField(
                blank=True, related_name="classes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
