# Generated by Django 5.1.2 on 2025-03-28 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_alter_classes_students"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="schedules",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.schedule",
            ),
        ),
    ]
