# Generated by Django 5.1.2 on 2025-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_classes_schedules"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeslot",
            name="time_slot_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
