# Generated by Django 5.1.2 on 2025-04-01 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0012_timeslot_time_slot_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
    ]
