# Generated by Django 5.1.2 on 2025-04-01 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_remove_schedule_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classes",
            name="schedules",
        ),
        migrations.AddField(
            model_name="schedule",
            name="scheduled_class",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.classes",
            ),
        ),
    ]
