# Generated by Django 5.1.2 on 2025-04-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0015_event"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="scheduled_class",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="user",
        ),
        migrations.RemoveField(
            model_name="timeslot",
            name="fitness_plan",
        ),
        migrations.DeleteModel(
            name="Activity",
        ),
        migrations.DeleteModel(
            name="Schedule",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
    ]
