# Generated by Django 5.1.2 on 2025-04-02 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_remove_schedule_scheduled_class_remove_schedule_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "scheduled_class",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.classes",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time_slot_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "day_of_week",
                    models.CharField(
                        choices=[
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Sunday", "Sunday"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "start_time",
                    models.CharField(
                        choices=[
                            ("06:00 AM", "06:00 AM"),
                            ("06:30 AM", "06:30 AM"),
                            ("07:00 AM", "07:00 AM"),
                            ("07:30 AM", "07:30 AM"),
                            ("08:00 AM", "08:00 AM"),
                            ("08:30 AM", "08:30 AM"),
                            ("09:00 AM", "09:00 AM"),
                            ("09:30 AM", "09:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("01:00 PM", "01:00 PM"),
                            ("01:30 PM", "01:30 PM"),
                            ("02:00 PM", "02:00 PM"),
                            ("02:30 PM", "02:30 PM"),
                            ("03:00 PM", "03:00 PM"),
                            ("03:30 PM", "03:30 PM"),
                            ("04:00 PM", "04:00 PM"),
                            ("04:30 PM", "04:30 PM"),
                            ("05:00 PM", "05:00 PM"),
                            ("05:30 PM", "05:30 PM"),
                            ("06:00 PM", "06:00 PM"),
                            ("06:30 PM", "06:30 PM"),
                            ("07:00 PM", "07:00 PM"),
                            ("07:30 PM", "07:30 PM"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "end_time",
                    models.CharField(
                        choices=[
                            ("06:00 AM", "06:00 AM"),
                            ("06:30 AM", "06:30 AM"),
                            ("07:00 AM", "07:00 AM"),
                            ("07:30 AM", "07:30 AM"),
                            ("08:00 AM", "08:00 AM"),
                            ("08:30 AM", "08:30 AM"),
                            ("09:00 AM", "09:00 AM"),
                            ("09:30 AM", "09:30 AM"),
                            ("10:00 AM", "10:00 AM"),
                            ("10:30 AM", "10:30 AM"),
                            ("11:00 AM", "11:00 AM"),
                            ("11:30 AM", "11:30 AM"),
                            ("12:00 PM", "12:00 PM"),
                            ("12:30 PM", "12:30 PM"),
                            ("01:00 PM", "01:00 PM"),
                            ("01:30 PM", "01:30 PM"),
                            ("02:00 PM", "02:00 PM"),
                            ("02:30 PM", "02:30 PM"),
                            ("03:00 PM", "03:00 PM"),
                            ("03:30 PM", "03:30 PM"),
                            ("04:00 PM", "04:00 PM"),
                            ("04:30 PM", "04:30 PM"),
                            ("05:00 PM", "05:00 PM"),
                            ("05:30 PM", "05:30 PM"),
                            ("06:00 PM", "06:00 PM"),
                            ("06:30 PM", "06:30 PM"),
                            ("07:00 PM", "07:00 PM"),
                            ("07:30 PM", "07:30 PM"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "fitness_plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeslots",
                        to="app.schedule",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "timeslot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="app.timeslot",
                    ),
                ),
            ],
        ),
    ]
