# Generated by Django 5.1.2 on 2025-04-03 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0018_remove_schedule_scheduled_class_remove_schedule_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClassCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "class_name",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar",
                        to="app.classes",
                    ),
                ),
            ],
        ),
    ]
