# Generated by Django 5.1.2 on 2025-04-03 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0019_classcalendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="class_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="app.classes",
            ),
        ),
    ]
