# Generated by Django 5.1.2 on 2025-04-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_cart_payment"),
        ("app", "0020_event_class_item"),
    ]

    operations = []
