# Generated by Django 5.1.2 on 2025-04-11 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0023_notification"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
