# Generated by Django 5.1.2 on 2025-04-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_notification_related_class_notification_requester'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
