# Generated by Django 5.1.2 on 2025-04-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0027_coach_first_name_coach_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="coach",
            name="linked_in",
            field=models.URLField(blank=True, null=True),
        ),
    ]
