# Generated by Django 5.1.2 on 2025-04-16 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0028_coach_linked_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
