# Generated by Django 5.1.2 on 2025-04-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0029_event_location_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="location_address",
        ),
    ]
