# Generated by Django 5.1.2 on 2025-04-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0030_remove_event_location_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="color",
            field=models.CharField(default="#ff7c00", max_length=7),
        ),
    ]
