# Generated by Django 5.1.2 on 2025-04-17 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0031_event_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meeting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=45.0, max_digits=10),
                ),
            ],
        ),
    ]
