# Generated by Django 5.1.2 on 2025-04-17 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0032_meeting"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
