# Generated by Django 5.1.2 on 2025-04-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0033_meeting_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="products",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
