# Generated by Django 5.1.2 on 2025-04-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0036_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="grade_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("prek-4", "PreK - 4th Grade"),
                    ("5-7", "5th - 7th Grade"),
                    ("8-10", "8th - 10th Grade"),
                    ("11-12-college", "11th - 12th Grade & College Student"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
