# Generated by Django 5.1.2 on 2025-04-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0037_profile_grade_range"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="grade_range",
        ),
        migrations.AddField(
            model_name="meeting",
            name="phase",
            field=models.CharField(
                choices=[
                    ("phase_1", "Phase 1: Introduction & Basics"),
                    ("phase_2", "Phase 2: Skill Reinforcement"),
                ],
                default="phase_1",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="meeting",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
