# Generated by Django 5.1.2 on 2025-04-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0038_remove_profile_grade_range_meeting_phase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="grade_range",
            field=models.CharField(
                choices=[
                    ("prek_4th", "PreK - 4th Grade"),
                    ("5th_7th", "5th - 7th Grade"),
                    ("8th_10th", "8th - 10th Grade"),
                    ("11th_12th_college", "11th - 12th Grade & College Students"),
                ],
                default="prek_4th",
                max_length=20,
            ),
        ),
    ]
