# Generated by Django 5.1.2 on 2025-04-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0039_meeting_grade_range"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=10,
            ),
        ),
    ]
