# Generated by Django 5.1.2 on 2025-04-24 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_meeting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('equipment', 'Equipment'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
