# Generated by Django 5.1.2 on 2025-04-23 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0040_meeting_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="meeting",
            name="exact_grade",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
