# Generated by Django 5.1.2 on 2025-04-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_merge_0041_meeting_exact_grade_0041_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_pics'),
        ),
    ]
