# Generated by Django 5.1.2 on 2025-04-30 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_alter_products_image'),
        ('app', '0043_rename_description_products_long_description_and_more'),
    ]

    operations = [
    ]
