# Generated by Django 5.1.2 on 2025-05-01 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_merge_20250430_1101"),
        ("app", "0044_merge_20250430_1106"),
    ]

    operations = []
