# Generated by Django 5.1.2 on 2025-05-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_merge_20250501_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='phase',
            field=models.CharField(choices=[('phase_1', 'Phase 1: Introduction & Basics'), ('phase_2', 'Phase 2: Skill Reinforcement'), ('phase_3', 'Phase 3: Custom Session')], default='phase_1', max_length=10),
        ),
    ]
